// Produce interface model
export interface Product {
    productId?: string; // Make productId optional since it will be generated by the database
    productName: string;
    productDescription: string;
    productPrice: number;
    productGender: string;
    productCategory: string;
    productBrand: string;
    productSize: number;
    productColor: string;
    productStock: number;
    productImage: string;
    productAmountSold: number;
    productCreatedAt: Date;
    productUpdatedAt?: Date;
}

export function validate(product: Product): string {
    if (!product.productName || product.productName.length === 0) {
        return "Product name is required.";
    }

    if (!product.productDescription || product.productDescription.length === 0) {
        return "Product description is required.";
    }

    if (!product.productPrice || isNaN(product.productPrice) || product.productPrice <= 0) {
        return "Invalid product price.";
    }

    if (!product.productCategory || product.productCategory.length === 0) {
        return "Product category is required.";
    }

    if (!product.productBrand || product.productBrand.length === 0) {
        return "Product brand is required.";
    }

    if (!product.productSize || isNaN(product.productSize) || product.productSize <= 0) {
        return "Invalid product size.";
    }

    if (!product.productColor || product.productColor.length === 0) {
        return "Product color is required.";
    }

    if (!product.productStock || isNaN(product.productStock) || product.productStock < 0) {
        return "Invalid product stock.";
    }

    if (!product.productImage || product.productImage.length === 0) {
        return "Product image is required.";
    }

    if (!product.productCreatedAt || !(product.productCreatedAt instanceof Date)) {
        return "Invalid created date.";
    }

    if (!product.productUpdatedAt || !(product.productUpdatedAt instanceof Date)) {
        return "Invalid updated date.";
    }

    return "";
}