// Produce interface model
export interface Product {
    productUpdatedAt?: Date;
    productSize?: string[];
    productCategory: string;
    productBrand: string;
    productCreatedAt: Date;

    // Display Data
    productId?: string; // Make productId optional since it will be generated by the database
    productName: string;
    productDescription: string;
    productPrice: number;
    productGender: string;
    productImage: string;
    productAmountSold: number;
    productColorVarietyDetail?: ProductColorVarietyDetail[];
}

export interface ProductColorVarietyDetail {
    productColor: string;
    productSize: string[];
    productStock: number[];
}

export function validateProduct(product: Product): string {
    if (!product.productName || product.productName.length === 0) {
        return "Product name is required.";
    }

    if (!product.productDescription || product.productDescription.length === 0) {
        return "Product description is required.";
    }

    if (!product.productPrice || isNaN(product.productPrice) || product.productPrice <= 0) {
        return "Invalid product price.";
    }

    if (!product.productCategory || product.productCategory.length === 0) {
        return "Product category is required.";
    }

    if (!product.productBrand || product.productBrand.length === 0) {
        return "Product brand is required.";
    }

    if (!product.productImage || product.productImage.length === 0) {
        return "Product image is required.";
    }

    if (!product.productCreatedAt || !(product.productCreatedAt instanceof Date)) {
        return "Invalid created date.";
    }

    return "";
}

export function validateProductColorVarietyDetail(productDetail: ProductColorVarietyDetail): string {
    if (!productDetail.productColor || productDetail.productColor.length === 0) {
        return "Product color is required.";
    }

    return "";
}

export interface ProductDisplay {
    productId?: string;
    productName: string;
    productDescription: string;
    productPrice: number;
    productGender: string;
    productImage: string;
    productAmountSold: number;
    productColorVarietyDetail?: ProductColorVarietyDetail[];
}

